export type PluralCategory = "zero" | "one" | "two" | "few" | "many" | "other";

export function af(n: number | string): "one" | "other";
export function ak(n: number | string): "one" | "other";
export function am(n: number | string): "one" | "other";
export function an(n: number | string): "one" | "other";
export function ar(n: number | string): "zero" | "one" | "two" | "few" | "many" | "other";
export function ars(n: number | string): "zero" | "one" | "two" | "few" | "many" | "other";
export function as(n: number | string): "one" | "other";
export function asa(n: number | string): "one" | "other";
export function ast(n: number | string): "one" | "other";
export function az(n: number | string): "one" | "other";
export function be(n: number | string): "one" | "few" | "many" | "other";
export function bem(n: number | string): "one" | "other";
export function bez(n: number | string): "one" | "other";
export function bg(n: number | string): "one" | "other";
export function bho(n: number | string): "one" | "other";
export function bm(n: number | string): "other";
export function bn(n: number | string): "one" | "other";
export function bo(n: number | string): "other";
export function br(n: number | string): "one" | "two" | "few" | "many" | "other";
export function brx(n: number | string): "one" | "other";
export function bs(n: number | string): "one" | "few" | "other";
export function ca(n: number | string): "one" | "other";
export function ce(n: number | string): "one" | "other";
export function ceb(n: number | string): "one" | "other";
export function cgg(n: number | string): "one" | "other";
export function chr(n: number | string): "one" | "other";
export function ckb(n: number | string): "one" | "other";
export function cs(n: number | string): "one" | "few" | "many" | "other";
export function cy(n: number | string): "zero" | "one" | "two" | "few" | "many" | "other";
export function da(n: number | string): "one" | "other";
export function de(n: number | string): "one" | "other";
export function dsb(n: number | string): "one" | "two" | "few" | "other";
export function dv(n: number | string): "one" | "other";
export function dz(n: number | string): "other";
export function ee(n: number | string): "one" | "other";
export function el(n: number | string): "one" | "other";
export function en(n: number | string): "one" | "other";
export function eo(n: number | string): "one" | "other";
export function es(n: number | string): "one" | "other";
export function et(n: number | string): "one" | "other";
export function eu(n: number | string): "one" | "other";
export function fa(n: number | string): "one" | "other";
export function ff(n: number | string): "one" | "other";
export function fi(n: number | string): "one" | "other";
export function fil(n: number | string): "one" | "other";
export function fo(n: number | string): "one" | "other";
export function fr(n: number | string): "one" | "other";
export function fur(n: number | string): "one" | "other";
export function fy(n: number | string): "one" | "other";
export function ga(n: number | string): "one" | "two" | "few" | "many" | "other";
export function gd(n: number | string): "one" | "two" | "few" | "other";
export function gl(n: number | string): "one" | "other";
export function gsw(n: number | string): "one" | "other";
export function gu(n: number | string): "one" | "other";
export function guw(n: number | string): "one" | "other";
export function gv(n: number | string): "one" | "two" | "few" | "many" | "other";
export function ha(n: number | string): "one" | "other";
export function haw(n: number | string): "one" | "other";
export function he(n: number | string): "one" | "two" | "many" | "other";
export function hi(n: number | string): "one" | "other";
export function hr(n: number | string): "one" | "few" | "other";
export function hsb(n: number | string): "one" | "two" | "few" | "other";
export function hu(n: number | string): "one" | "other";
export function hy(n: number | string): "one" | "other";
export function ia(n: number | string): "one" | "other";
export function id(n: number | string): "other";
export function ig(n: number | string): "other";
export function ii(n: number | string): "other";
export function _in(n: number | string): "other";
export function io(n: number | string): "one" | "other";
export function is(n: number | string): "one" | "other";
export function it(n: number | string): "one" | "other";
export function iu(n: number | string): "one" | "two" | "other";
export function iw(n: number | string): "one" | "two" | "many" | "other";
export function ja(n: number | string): "other";
export function jbo(n: number | string): "other";
export function jgo(n: number | string): "one" | "other";
export function ji(n: number | string): "one" | "other";
export function jmc(n: number | string): "one" | "other";
export function jv(n: number | string): "other";
export function jw(n: number | string): "other";
export function ka(n: number | string): "one" | "other";
export function kab(n: number | string): "one" | "other";
export function kaj(n: number | string): "one" | "other";
export function kcg(n: number | string): "one" | "other";
export function kde(n: number | string): "other";
export function kea(n: number | string): "other";
export function kk(n: number | string): "one" | "other";
export function kkj(n: number | string): "one" | "other";
export function kl(n: number | string): "one" | "other";
export function km(n: number | string): "other";
export function kn(n: number | string): "one" | "other";
export function ko(n: number | string): "other";
export function ks(n: number | string): "one" | "other";
export function ksb(n: number | string): "one" | "other";
export function ksh(n: number | string): "zero" | "one" | "other";
export function ku(n: number | string): "one" | "other";
export function kw(n: number | string): "zero" | "one" | "two" | "few" | "many" | "other";
export function ky(n: number | string): "one" | "other";
export function lag(n: number | string): "zero" | "one" | "other";
export function lb(n: number | string): "one" | "other";
export function lg(n: number | string): "one" | "other";
export function lkt(n: number | string): "other";
export function ln(n: number | string): "one" | "other";
export function lo(n: number | string): "other";
export function lt(n: number | string): "one" | "few" | "many" | "other";
export function lv(n: number | string): "zero" | "one" | "other";
export function mas(n: number | string): "one" | "other";
export function mg(n: number | string): "one" | "other";
export function mgo(n: number | string): "one" | "other";
export function mk(n: number | string): "one" | "other";
export function ml(n: number | string): "one" | "other";
export function mn(n: number | string): "one" | "other";
export function mo(n: number | string): "one" | "few" | "other";
export function mr(n: number | string): "one" | "other";
export function ms(n: number | string): "other";
export function mt(n: number | string): "one" | "few" | "many" | "other";
export function my(n: number | string): "other";
export function nah(n: number | string): "one" | "other";
export function naq(n: number | string): "one" | "two" | "other";
export function nb(n: number | string): "one" | "other";
export function nd(n: number | string): "one" | "other";
export function ne(n: number | string): "one" | "other";
export function nl(n: number | string): "one" | "other";
export function nn(n: number | string): "one" | "other";
export function nnh(n: number | string): "one" | "other";
export function no(n: number | string): "one" | "other";
export function nqo(n: number | string): "other";
export function nr(n: number | string): "one" | "other";
export function nso(n: number | string): "one" | "other";
export function ny(n: number | string): "one" | "other";
export function nyn(n: number | string): "one" | "other";
export function om(n: number | string): "one" | "other";
export function or(n: number | string): "one" | "other";
export function os(n: number | string): "one" | "other";
export function osa(n: number | string): "other";
export function pa(n: number | string): "one" | "other";
export function pap(n: number | string): "one" | "other";
export function pl(n: number | string): "one" | "few" | "many" | "other";
export function prg(n: number | string): "zero" | "one" | "other";
export function ps(n: number | string): "one" | "other";
export function pt(n: number | string): "one" | "other";
export function pt_PT(n: number | string): "one" | "other";
export function rm(n: number | string): "one" | "other";
export function ro(n: number | string): "one" | "few" | "other";
export function rof(n: number | string): "one" | "other";
export function root(n: number | string): "other";
export function ru(n: number | string): "one" | "few" | "many" | "other";
export function rwk(n: number | string): "one" | "other";
export function sah(n: number | string): "other";
export function saq(n: number | string): "one" | "other";
export function sc(n: number | string): "one" | "other";
export function scn(n: number | string): "one" | "other";
export function sd(n: number | string): "one" | "other";
export function sdh(n: number | string): "one" | "other";
export function se(n: number | string): "one" | "two" | "other";
export function seh(n: number | string): "one" | "other";
export function ses(n: number | string): "other";
export function sg(n: number | string): "other";
export function sh(n: number | string): "one" | "few" | "other";
export function shi(n: number | string): "one" | "few" | "other";
export function si(n: number | string): "one" | "other";
export function sk(n: number | string): "one" | "few" | "many" | "other";
export function sl(n: number | string): "one" | "two" | "few" | "other";
export function sma(n: number | string): "one" | "two" | "other";
export function smi(n: number | string): "one" | "two" | "other";
export function smj(n: number | string): "one" | "two" | "other";
export function smn(n: number | string): "one" | "two" | "other";
export function sms(n: number | string): "one" | "two" | "other";
export function sn(n: number | string): "one" | "other";
export function so(n: number | string): "one" | "other";
export function sq(n: number | string): "one" | "other";
export function sr(n: number | string): "one" | "few" | "other";
export function ss(n: number | string): "one" | "other";
export function ssy(n: number | string): "one" | "other";
export function st(n: number | string): "one" | "other";
export function su(n: number | string): "other";
export function sv(n: number | string): "one" | "other";
export function sw(n: number | string): "one" | "other";
export function syr(n: number | string): "one" | "other";
export function ta(n: number | string): "one" | "other";
export function te(n: number | string): "one" | "other";
export function teo(n: number | string): "one" | "other";
export function th(n: number | string): "other";
export function ti(n: number | string): "one" | "other";
export function tig(n: number | string): "one" | "other";
export function tk(n: number | string): "one" | "other";
export function tl(n: number | string): "one" | "other";
export function tn(n: number | string): "one" | "other";
export function to(n: number | string): "other";
export function tr(n: number | string): "one" | "other";
export function ts(n: number | string): "one" | "other";
export function tzm(n: number | string): "one" | "other";
export function ug(n: number | string): "one" | "other";
export function uk(n: number | string): "one" | "few" | "many" | "other";
export function ur(n: number | string): "one" | "other";
export function uz(n: number | string): "one" | "other";
export function ve(n: number | string): "one" | "other";
export function vi(n: number | string): "other";
export function vo(n: number | string): "one" | "other";
export function vun(n: number | string): "one" | "other";
export function wa(n: number | string): "one" | "other";
export function wae(n: number | string): "one" | "other";
export function wo(n: number | string): "other";
export function xh(n: number | string): "one" | "other";
export function xog(n: number | string): "one" | "other";
export function yi(n: number | string): "one" | "other";
export function yo(n: number | string): "other";
export function yue(n: number | string): "other";
export function zh(n: number | string): "other";
export function zu(n: number | string): "one" | "other";
