export type PluralCategory = "zero" | "one" | "two" | "few" | "many" | "other";

export function af(n: number | string): "other";
export function am(n: number | string): "other";
export function an(n: number | string): "other";
export function ar(n: number | string): "other";
export function as(n: number | string): "one" | "two" | "few" | "many" | "other";
export function az(n: number | string): "one" | "few" | "many" | "other";
export function be(n: number | string): "few" | "other";
export function bg(n: number | string): "other";
export function bn(n: number | string): "one" | "two" | "few" | "many" | "other";
export function bs(n: number | string): "other";
export function ca(n: number | string): "one" | "two" | "few" | "other";
export function ce(n: number | string): "other";
export function cs(n: number | string): "other";
export function cy(n: number | string): "zero" | "one" | "two" | "few" | "many" | "other";
export function da(n: number | string): "other";
export function de(n: number | string): "other";
export function dsb(n: number | string): "other";
export function el(n: number | string): "other";
export function en(n: number | string): "one" | "two" | "few" | "other";
export function es(n: number | string): "other";
export function et(n: number | string): "other";
export function eu(n: number | string): "other";
export function fa(n: number | string): "other";
export function fi(n: number | string): "other";
export function fil(n: number | string): "one" | "other";
export function fr(n: number | string): "one" | "other";
export function fy(n: number | string): "other";
export function ga(n: number | string): "one" | "other";
export function gd(n: number | string): "one" | "two" | "few" | "other";
export function gl(n: number | string): "other";
export function gsw(n: number | string): "other";
export function gu(n: number | string): "one" | "two" | "few" | "many" | "other";
export function he(n: number | string): "other";
export function hi(n: number | string): "one" | "two" | "few" | "many" | "other";
export function hr(n: number | string): "other";
export function hsb(n: number | string): "other";
export function hu(n: number | string): "one" | "other";
export function hy(n: number | string): "one" | "other";
export function ia(n: number | string): "other";
export function id(n: number | string): "other";
export function _in(n: number | string): "other";
export function is(n: number | string): "other";
export function it(n: number | string): "many" | "other";
export function iw(n: number | string): "other";
export function ja(n: number | string): "other";
export function ka(n: number | string): "one" | "many" | "other";
export function kk(n: number | string): "many" | "other";
export function km(n: number | string): "other";
export function kn(n: number | string): "other";
export function ko(n: number | string): "other";
export function kw(n: number | string): "one" | "many" | "other";
export function ky(n: number | string): "other";
export function lo(n: number | string): "one" | "other";
export function lt(n: number | string): "other";
export function lv(n: number | string): "other";
export function mk(n: number | string): "one" | "two" | "many" | "other";
export function ml(n: number | string): "other";
export function mn(n: number | string): "other";
export function mo(n: number | string): "one" | "other";
export function mr(n: number | string): "one" | "two" | "few" | "other";
export function ms(n: number | string): "one" | "other";
export function my(n: number | string): "other";
export function nb(n: number | string): "other";
export function ne(n: number | string): "one" | "other";
export function nl(n: number | string): "other";
export function or(n: number | string): "one" | "two" | "few" | "many" | "other";
export function pa(n: number | string): "other";
export function pl(n: number | string): "other";
export function prg(n: number | string): "other";
export function ps(n: number | string): "other";
export function pt(n: number | string): "other";
export function ro(n: number | string): "one" | "other";
export function root(n: number | string): "other";
export function ru(n: number | string): "other";
export function sc(n: number | string): "many" | "other";
export function scn(n: number | string): "many" | "other";
export function sd(n: number | string): "other";
export function sh(n: number | string): "other";
export function si(n: number | string): "other";
export function sk(n: number | string): "other";
export function sl(n: number | string): "other";
export function sq(n: number | string): "one" | "many" | "other";
export function sr(n: number | string): "other";
export function sv(n: number | string): "one" | "other";
export function sw(n: number | string): "other";
export function ta(n: number | string): "other";
export function te(n: number | string): "other";
export function th(n: number | string): "other";
export function tk(n: number | string): "few" | "other";
export function tl(n: number | string): "one" | "other";
export function tr(n: number | string): "other";
export function uk(n: number | string): "few" | "other";
export function ur(n: number | string): "other";
export function uz(n: number | string): "other";
export function vi(n: number | string): "one" | "other";
export function yue(n: number | string): "other";
export function zh(n: number | string): "other";
export function zu(n: number | string): "other";
